dataset: S-FFSD

trainfeature: data/trf_3d.npy
trainlabel: data/trl_3d.npy
testfeature: data/tef_3d.npy
testlabel: data/tel_3d.npy

test_size: 0.2

epochs: 20
#epochs: 40
batch_size: 256
attention_hidden_dim: 150
lr: 0.0001
device: cuda:0